### PR TITLE
Adding the ability to hold down keys rather than only tapping them.

### PR DESCRIPTION
**Pull request by amoldybuffalo**
I wanted to use this software to use a midi keyboard for games, but obviously that often requires holding down a key. I saw that this had not yet been implemented, so I decided I would do it myself. If my code is too garbage or I need to alter the feature in any way just tell me what to fix and I'll do it.

Thank you!

### CODE REVIEW

**Comment by m10x** [comment]
Hi @amoldybuffalo,
thanks for your PR! I've tested it and there are a few problems:
- When HELD is disabled, everything write and keypress fires twice. Once when Pressing a button and once when releasing it.
- When Keypress is using more than one key, the tool crashes
```
2024/01/28 12:25:23 Keypress: a,ctrl,alt,cmd
2024/01/28 12:25:32 saving preferences
2024/01/28 12:25:37 starting note F7 (int: 89) on channel 0 with velocity 127
2024/01/28 12:25:37 Held is on
panic: interface conversion: interface {} is []string, not string

goroutine 261 [running, locked to thread]:
github.com/go-vgo/robotgo.ToStrings(...)
        /home/max/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.0/key.go:469
github.com/go-vgo/robotgo.KeyToggle({0xbf8065, 0x1}, {0xc00168b518?, 0x1?, 0x1?})
        /home/max/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.0/key.go:564 +0x528
github.com/go-vgo/robotgo.KeyDown(...)
        /home/max/go/pkg/mod/github.com/go-vgo/robotgo@v0.110.0/key.go:583
github.com/m10x/midi2key-ng/pkg/pkgMidi.keyDown({0xbf8065, 0xe})
```
- When Choosing Keypress (Combo) the Held Checkbox is disabled. Thus Held cannot be enabled or disabled.

**Comment by amoldybuffalo** [comment]
Thank you. I'll work on these bugs.

**Comment by amoldybuffalo** [comment]
Okay, all of those bugs should be fixed. I apologize for not checking very thoroughly for issues before making the PR.

**Comment by amoldybuffalo** [comment]
Oh, sorry, I should probably ping you. @m10x

**Comment by m10x** [comment]
Hello, I finally had time to test your bug fixes. Your added feature seems to be working flawlessly now. Thanks for the addition! A small modification of the table is still needed, so that the "held" column is visible without resizing the window. I'll do this after merging your pull request :)

**Comment by m10x** [comment]
Oops, misclicked. Now it's merged.

**Pull request merged**
